// Compliance pack: `node tools/compliance.mjs` writes COMPLIANCE.md from the audited registry (js/data/licences.json).
// One row per source or component that is contacted or shipped, for each deployment mode, with its licence, the
// obligation, where the attribution is shown, the sentence relied on with its address and the date it was read, and
// the questions that still need a human decision. The same content is shown in the app (About → Compliance pack).
// Nothing here is legal advice: it is a record a lawyer can check line by line.

import { readFile, writeFile } from 'node:fs/promises';
import { join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { complianceRows, complianceQuestions } from '../js/core/compliance.js';

const root = resolve(fileURLToPath(new URL('..', import.meta.url)));
const reg = JSON.parse(await readFile(join(root, 'js/data/licences.json'), 'utf8'));
const cell = (v) => String(v ?? '').replace(/\|/g, '\\|').replace(/\s*\n\s*/g, ' ');
const table = (cols, rows) => [`| ${cols.join(' | ')} |`, `|${cols.map(() => '---').join('|')}|`, ...rows.map((r) => `| ${r.map(cell).join(' | ')} |`)].join('\n');
const modes = [['commercial', 'Commercial deployment (`"commercial": true`, no keys)'], ['nonCommercial', 'Non-commercial deployment (default configuration)']];
const qs = complianceQuestions(reg);
const out = [`# Compliance pack — AeroSuite 26`, '',
  `Generated by \`tools/compliance.mjs\` from \`js/data/licences.json\`. Terms were read on ${reg.retrieved}. Every row gives the page and the sentence the conclusion rests on. This is a record for review, not legal advice.`, '',
  `## Questions that need a decision (${qs.length})`, '', qs.length ? qs.map((q, k) => `${k + 1}. **${q.name}** — ${q.question}`).join('\n') : 'None.', '',
  ...modes.flatMap(([mode, title]) => { const rows = complianceRows(reg, mode); return [`## ${title}`, '', `${rows.length} sources and datasets are contacted or shipped in this mode.`, '',
    table(['Source', 'How it is used', 'Licence or terms', 'Obligations', 'Attribution shown at', 'Sentence relied on', 'Address', 'Read on'], rows.map((r) => [r.name, r.use, r.licence, r.obligations, r.shownAt, r.quote, r.url, r.retrieved])), '']; }),
  '## Not used', '', table(['Source', 'Why', 'Replaced by', 'Sentence relied on', 'Address'], reg.sources.filter((s) => s.used === false || (s.usedInCommercial === false && s.class !== 'commercial-ok')).map((s) => [s.name, s.used === false ? 'Removed in every mode' : `Not in commercial mode (${s.class})`, s.replacement || '', s.quote ? `“${s.quote}”` : '', s.url || ''])), '',
  '## Software components', '', table(['Component', 'Version', 'Licence', 'Shipped', 'Licence text', 'Modifications', 'Obligations'], reg.components.map((c) => [c.name, c.version, c.licence, c.shipped ? 'yes' : 'no (development tool)', c.licenceFile, c.modifications, (c.obligations || []).join('; ')])), ''].join('\n');
await writeFile(join(root, 'COMPLIANCE.md'), out);
console.log(`COMPLIANCE.md: ${complianceRows(reg, 'commercial').length} rows (commercial), ${complianceRows(reg, 'nonCommercial').length} rows (non-commercial), ${qs.length} open questions`);
